---
title: Administración de la Cadena de Suministro 5th (Sunil Chopra)
author: Osvaldo Roche
date: '2024-05-06'
slug: administracion-cadena-de-suministro-sunil-chopra
categories:
  - Resumen
tags:
  - Books
subtitle: ''
summary: ''
authors: []
lastmod: '2024-05-06T19:03:53-06:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


# CAPITULO 1. Qué Es la Cadena de Suministro

Una cadena de suministro se compone de todas las partes involucradas, directa o indirectamente, para satisfacer la petición de un cliente. La cadena de suministro incluye todas las funciones implicadas en la recepción y satisfacción del pedido de un cliente.Asi que el propósito primordial de cualquier cadena de suministro es satisfacer las necesidades del cliente y, en el proceso generar una ganancia para si misma.

## Objetivo de una cadena de suministro

El objetivo de toda cadena de suministro debe ser maximizar el valor total generado. **El valor** (también conocido como superávit de la cadena de suministro) que genera una cadena de suministro **es la diferencia entre lo que el cliente paga por el producto final y los costos en que incurre la cadena para cumplir con el pedido**. De otro modo:

$Valor = Supéravit~cadena~suministro=Pago~Final~-~Costos$

La diferencia entre el valor del producto y su precio permanece con el cliente como súperavit para el cliente (SC). Es decir:

$SC = Valor~Producto~-Precio~Producto$

La diferencia entre el superávit del cliente y el superávit de la cadena de suministro se transforma en **rentabilidad de la cadena de suministro**(RCS).

$RCS = Valor - SC$

**Ejemplo: un cliente que compra un ruteador inalámbrico en Best Buy paga `$60.00`, que representan el ingreso que la cadena de suministro recibe. Los clientes que compran el ruteador lo valoran en más o menos `$60`. Best Buy y otras etapas de la cadena de suministro incurren en costos de `$55` para transferir información, producir componentes, almacenarlos, transportarlos, transferir fondos.**

```{r}
# Datos obtenidos
precio = 60
valorProducto = 60
costos = 55

# Calculo del RCS
RCS = precio - costos

# Resultado
RCS
```

En este ejemplo la RCS es de `$5.00`

De manera que una eficaz administración de la cadena de suministro implica la administración de sus activos y flujos de productos, información y fondos para máximizar su superávit. El argumento del superávit de la cadena de suministro implica que conforme la venta al detalle comience a consolidarse, el papel de los distribuidores disminuirá. 

## Fases de decisión en una cadena de suministro

Cada desición debe tomarse para incrmentar el superavit de la cadena de suministro. Las fases de decisión en una cadena de suministro pueden clasificarse como de diseño, de planeación y de operaciones, según el marco de tiempo durante el cual se apliquen las decisiones tomadas.

**1.Estrategia o diseño de la cadena de suministro.** Durante esta fase, una compañía decide cómo estructurar la cadena de suministro para los siguientes años.Aquí se establece cómo se asignarán los recursos y qué procesos realizará cada etapa.

**2. Planeación de la cadena de suministro.** Para decisiones tomadas durante esta fase, el marco de tiempo considerado es de un trimestre a un año. La meta de la planeación es maximizar el superávit de la cadena de suministro que se puede generar a lo largo del horizonte de planeación dadas las restricciones establecidas durante la fase estratégica o de diseño.La planeación incluye tomar decisiones en relación a qué mercados serán abastecidos desde qué lugares, la subcontratación de la fabricación, las políticas de inventario que se seguirán, y la temporización y tamaño de las promociones de comercialización y precios.

**3. Operación de la cadena de suministro.** Durante esta fase, las compañías toman decisiones respecto de pedidos de clientes individuales. En esta fase las empresas asignan inventario o producción a pedidos individuales, fijan la fecha en que el pedido se debe terminar, generan listas de selección en un almacén, asignan un pedido a un modo de embarque particular, establecen programas de entrega de los camiones y colocan pedidos de reabastecimiento.

## Visualización de los Procesos de una Cadena de Suministros


Hay dos maneras de ver los procesos realizados en una Cadena de suministro:

1. Visualización de cliclo

2. Visualización de empuje/tiron

### Visualización de cliclo

Este se divide en cuatro ciclos:

+ Ciclo de pedido del cliente
+ Ciclo de reabastecimiento
+ Ciclo de fabricación
+ Ciclo de adquisición

Cada uno de estos ciclos consta de 6 subprocesos:

- El proveedor comercializa el producto
- El comprador coloca un pedido
- El proveedor recibe el pedido
- El proveedor surte el pedido
- El comprador recibe el suministro
- El comprador devuelve flujos inversos al proveedor

El objetivo del comprador es garanjtizar la disponibilidad del producto y alcanzar economías de escala en los pedidos. El proveedor trata de pronosticar los pedidos del cliente y reducir el costo de recepción del pedido. De manera que cada uno es vendedor o comprador en algún momento del ciclo. 

Una visualización de ciclo de la cadena de suministro es útil cuando se consideran desiciones de operaciones porque especifica con claridad las funciones de cada mienbbro de la cadena. Por ejemplo, cuando se establicen sistemas de información para apoyar las operaciones de la cadena de suministro. 

### Visualización de empuje/tirón





















